name: test

on:
  push:
    branches:
      - master

jobs:
  testsolution:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['21']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build with Maven
        run: mvn -B verify

      - name: Create javadoc
        run: |
          javadoc -encoding utf8 -d javadoc -sourcepath src/main/java -subpackages minicp minicp
          mv javadoc /tmp/.

      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Add new javadoc
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git rm -r *
          cp -r /tmp/javadoc/* .
          touch .nojekyll
          git add -A
          git commit -m "update javadoc" || echo "No changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}